Håndtering av uncaught exception for å finne årsak til restart av pods
navikt/fptilbake pull request #2686
Opened 2023-11-06 09:01 UTC by tendestad

2023-11-06 09:29 UTC, stiangre approved these changes

2023-11-06 09:56 UTC, jolarsen commented
@tendestad finner du ikke svaret fra AppDynamics ?

2023-11-07 06:07 UTC, mrsladek commented
Det virker noe overflodig... håndterer ikke kubernetes det selv? om /isAlive ikke svarer så blir det nok en restart uansett. Hva er det som ligger back denne endringen siden jeg ikke er i tråden fra starten?

2023-11-07 08:53 UTC, mrsladek requested changes
Dette virkes unyttig - restart logikk håndteres og styrres av kubernetes og de 3 endepunkter som er definert i naiserator.yaml konfig.

2024-03-12 13:25 UTC, closed without merging